---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyquant)
library(magrittr)
library(ggplot2)
```

```{r coke-pepsi}
# download daily prices for Coke and Pepsi stock from Yahoo Finance
coke <- tq_get("COKE", get = "stock.prices", 
               from = "2013-01-01", to = "2014-01-01")
pepsi <- tq_get("PEP", get = "stock.prices", 
                from = "2013-01-01", to = "2014-01-01")

# it is assumed that if Coke goes up on a particular day, 
# then so should Pepsi. 
# as a result, we focus on price changes of these two stocks

calculate_price_change <- function(stock_price_df) {
  price_change_df <- stock_price_df %>% 
    tq_mutate(select = adjusted, mutate_fun = diff.xts) %>% 
    dplyr::select(symbol, date, diff.xts) %>% 
    dplyr::filter(!is.na(diff.xts)) # the first entry naturally contains a missing value (NA) because there is no previous price
  
  return(price_change_df)
}


coke_price_change <- calculate_price_change(coke) 
pepsi_price_change <- calculate_price_change(pepsi)

# make a scatter plot of Coke versus Pepsi price changes over a year
# as shown in figure 6.1
coke_price_change %>% 
  dplyr::bind_rows(pepsi_price_change) %>% 
  tidyr::pivot_wider(id_cols = date, names_from = symbol, values_from = diff.xts) %>% 
  ggplot(aes(COKE, PEP)) + 
  geom_point(shape = 1, size = 3) + 
  theme_bw() + 
  labs(x = "Coke price changes", y = "Pepsi price changes", 
       title = "Pepsi versus Coke price changes")
```

